#!/usr/bin/env bash

if [ ! -f "docker-compose.yml" ]; then
    docker-init
fi
# TODO: Check if module already exists

PROJECT=${PWD##*/}

TMP_FOLDER=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
git clone git@gitlab.com:barbaris/docker-recipes.git /tmp/$TMP_FOLDER
rm -fr /tmp/$TMP_FOLDER/.git

while [ "$1" != "" ]; do
  MODULE=$1
  echo $MODULE
  sed -i -e s/skeleton/$PROJECT/g /tmp/$TMP_FOLDER/$MODULE/docker-compose-fragment.yml
  cat /tmp/$TMP_FOLDER/$MODULE/docker-compose-fragment.yml >> ./docker-compose.yml
  echo -en '\n'>>docker-compose.yml
  if [ -d "/tmp/$TMP_FOLDER/$MODULE/build" ]; then
      mkdir -p builds/
      cp -r /tmp/$TMP_FOLDER/$MODULE/build/ builds/
      mv builds/build builds/$MODULE
  fi
  shift
done

rm -fr /tmp/$TMP_FOLDER
