#!/usr/bin/env bash

if [ "$1" == "" ]
then
  echo Error: Alias is not specified
  exit 1
fi

PROJECT_NAME=${PWD##*/}

REGISTRY_FILE=${DOCKER_REGISTRY_FILE}

if [ "$REGISTRY_FILE" == "" ]
then
  REGISTRY_FILE=~/.docker-recipes-registry.csv
fi

if [ ! -f $REGISTRY_FILE ]
then
    echo File not found: $REGISTRY_FILE
    exit 1
fi

if [ "$1" == "list" ]
then
  cat $REGISTRY_FILE
  exit 0
fi

echo Recipes registry: $REGISTRY_FILE

while IFS=, read -r col1 col2
do
    if [ "$col1" == "$1" ]
    then
      URI=$col2
      break
    fi
done < $REGISTRY_FILE


COPY_GIT=0

while [ "$1" != "" ]; do
    case $1 in
        -g | --copy-git )
                                COPY_GIT=1
                                ;;
#        -i | --interactive )    interactive=1
#                                echo iii
#                                ;;
#        -h | --help )           usage
#                                echo hhh
#                                exit
#                                ;;
#        * )                     usage
#                                exit 1
    esac
    shift
done

if [ "$URI" == "" ]
then
  echo Error: Could not resolve URL by alias \"$1\"
  exit 1
else
  echo Found resource: $URI
  TMP_FOLDER=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
  git clone $URI /tmp/$TMP_FOLDER

  # Execute following line only if "-g" parameter is set
  if [ "$COPY_GIT" == "1" ]
  then
    cp -r /tmp/$TMP_FOLDER/.git/ ./
  fi
  rm -fr /tmp/$TMP_FOLDER/.git/

  # Replace all strings "skeleton" with project name if provided
  find /tmp/$TMP_FOLDER -type f -print0 | xargs -0 sed -i 's/skeleton/'$PROJECT_NAME'/g'

  # Copy not hidden files and directories
  cp -r /tmp/$TMP_FOLDER/* ./

  # Copy hidden files and directories
  cp -r /tmp/$TMP_FOLDER/.[^.]* ./

  rm -fr /tmp/$TMP_FOLDER
fi
