#!/usr/bin/env bash

if [ "$1" == "" ]
then
  echo Error: Alias is not specified
  exit 1
fi

REGISTRY_FILE=${DOCKER_REGISTRY_FILE}

if [ "$REGISTRY_FILE" == "" ]
then
  REGISTRY_FILE=~/.docker-recipes-registry.csv
fi

if [ ! -f /tmp/foo.txt ]; then
    echo File not found: $REGISTRY_FILE
    exit 1
fi

echo Recipes registry: $REGISTRY_FILE

while IFS=, read -r col1 col2
do
    if [ "$col1" == "$1" ]
    then
      URI=$col2
      break
    fi
done < $REGISTRY_FILE

if [ "$URI" == "" ]
then
  echo Error: Could not resolve URL by alias \"$1\"
  exit 1
else
  echo Found resource: $URI
  git clone $URI

  # TODO: Replace all strings "skeleton" with project name if provided
fi